### ISSUE TITLE
Bug: User cannot login when parsing creds for the first time

### ISSUE THREAD

**Issue by ghostleek** [String-sg/chergpt-starter-kit#26]
error: 

<img width="1657" alt="image" src="https://github.com/String-sg/chergpt-starter-kit/assets/44336310/3dcedc37-25d9-4bb1-99e9-3ed7b003d49b">

**Comment by ghostleek** [comment]
workaround: press login twice

**Comment by twahidin** [comment]
The st.rerun() is found in version 1.27 onwards ensure you have the correct library installed
