### ISSUE TITLE
seems like the tch1 and stu1 cannot login with the default password?

### ISSUE THREAD

**Issue by lookang** [String-sg/chergpt-starter-kit#4]
seems like the tch1 and stu1 cannot login with the default password?
![Screenshot 2023-09-21 at 10 51 55 PM](https://github.com/String-sg/chergpt-starter-kit/assets/20143558/7f90858e-cfd7-4613-92cc-9b0fb810e56c)

**Comment by lookang** [comment]
after administrator reset password, admin can reset all passwords of tch and stu.
wow managed to figure out

**Comment by ghostleek** [comment]
hmm @lookang thanks for flagging - will review and amend accordingly 
likely the accounts weren't seeded properly

**Comment by ghostleek** [comment]
resolved with v2!
