### ISSUE TITLE
seems like openAI key also cannot be enter? it seems to work if i add to secrets on streamlit

### ISSUE THREAD

**Issue by lookang** [String-sg/chergpt-starter-kit#5]
on https://starterkit.streamlit.app/
seems like openAI key also cannot be enter?

https://chergptlookang.streamlit.app/
it seems to work if i add to secrets on streamlit

**Comment by ghostleek** [comment]
will also review this

**Comment by twahidin** [comment]
Remove this and allow only api key to enter via secrets to ensure the function can function
