### ISSUE TITLE
can administrator set the GPT model to use?

### ISSUE THREAD

**Issue by lookang** [String-sg/chergpt-starter-kit#6]
openai_key = "XXXXXXX_YOUR_API_KEY"
default_db = "chergpt.db"
default_temp = 0
# default_model = "gpt-4"
default_model = "gpt-3.5"

can I use default_model = "gpt-3.5" instead?
didn't seems to work to 3.5 when i change the secrets on streamlit app- settings.
![Screenshot 2023-09-22 at 8 07 12 AM](https://github.com/String-sg/chergpt-starter-kit/assets/20143558/b30f0004-47b1-4551-b976-179a3653abd0)

**Comment by lookang** [comment]
gpt-3.5-turbo
got it to work. no worries
![Screenshot 2023-09-22 at 8 15 10 AM](https://github.com/String-sg/chergpt-starter-kit/assets/20143558/8cedd5b2-ca7d-48fd-84f6-1c52e5e48ec8)

**Comment by twahidin** [comment]
Thanks. @ghostleek maybe can add in the readme file the different GPT Model to use for st.secrets

**Comment by ghostleek** [comment]
<img width="867" alt="image" src="https://github.com/String-sg/chergpt-starter-kit/assets/44336310/430a3a22-2a3a-4640-b3e4-96717efb8c04">
closing this issue + added it explicitly in readme.md
